# flake8: noqa
# Generated by Django 4.0.3 on 2022-03-24 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Langs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_title', models.CharField(max_length=50, verbose_name='full_title')),
                ('iso_639_1', models.CharField(max_length=10, verbose_name='ISO 639-1')),
                ('iso_639_2', models.CharField(blank=True, max_length=10, verbose_name='ISO 639-2')),
            ],
            options={
                'verbose_name': 'lang',
                'verbose_name_plural': 'langs',
                'db_table': 'content"."langs',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path_to_video', models.CharField(max_length=255, verbose_name='path_to_video')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
                'db_table': 'content"."video',
            },
        ),
        migrations.CreateModel(
            name='AudioAndText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path_to_audio', models.CharField(max_length=255, verbose_name='path_to_audio')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('h1', models.CharField(max_length=50, verbose_name='h1')),
                ('description', models.TextField(verbose_name='description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lang', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='videos.langs')),
                ('video', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'verbose_name': 'audio_and_text',
                'verbose_name_plural': 'audio_and_texts',
                'db_table': 'content"."audio_and_text',
            },
        ),
    ]
