# flake8: noqa
# Generated by Django 4.0.3 on 2022-03-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioandtext',
            name='lang',
            field=models.ForeignKey(db_column='lang', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.langs'),
        ),
        migrations.AlterField(
            model_name='audioandtext',
            name='video',
            field=models.ForeignKey(db_column='video', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
        migrations.AddIndex(
            model_name='audioandtext',
            index=models.Index(fields=['title'], name='audio_and_text_title_idx'),
        ),
        migrations.AddIndex(
            model_name='audioandtext',
            index=models.Index(fields=['description'], name='audio_and_text_description_idx'),
        ),
    ]
