FROM python:3.9-slim

EXPOSE 8000/tcp

WORKDIR /app
COPY requirements.txt .
COPY .env .
RUN pip install --upgrade pip && pip install -r requirements.txt

WORKDIR /app/django_admin
COPY django_admin .

CMD python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000
