version: '3'
services:

    database:
        image: postgres:13
        expose:
            - "5432"
        env_file:
            - ".env"
        volumes:
            - data:/data

    admin:
        build:
            context: .
            dockerfile: src/Dockerfile.django_admin
        env_file:
            - ".env"
        depends_on:
            - database
        expose:
            - "8000"
        volumes:
            - videos:/videos
            - static:/app/static

    nginx:
        image: nginx:1.9.2
        volumes:
            - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./src/site.conf:/etc/nginx/conf.d/site.conf:ro
            - static:/static
        depends_on:
            - admin
        ports:
            - "80:80"


volumes:
    data:
    videos:
    static:
