version: '3'
services:

    database:
        image: postgres:13
        expose:
            - "5432"
        env_file:
            - ".env"
        volumes:
            -   data:/data

    admin:
        build:
            context: .
            dockerfile: src/Dockerfile.django_admin
        env_file:
            - ".env"
        depends_on:
            - database
        ports:
            - "8000:8000"
        volumes:
            -   videos:/videos

volumes:
    data:
    videos:
