version: '3'
services:

    database:
        image: postgres:13
        #        expose:
        #            - "5432"
        ports:
            - "5433:5432"
        env_file:
            - ".env"
        volumes:
            - data:/data

    elastic:
        build:
            context: .
            dockerfile: src/Dockerfile.elastic
        ports:
            - "9200:9200"
        volumes:
            - elastic_data:/elastic_data
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms2000m -Xmx2000m
        depends_on:
            - database

    admin:
        build:
            context: .
            dockerfile: src/Dockerfile.django_admin
        env_file:
            - ".env"
        depends_on:
            - database
        expose:
            - "8000"
        volumes:
            - videos:/videos
            - static:/app/static
            - media_source:/app/media

    etl:
        build:
            context: .
            dockerfile: src/Dockerfile.etl
        env_file:
            - "etl/.env_etl"
        volumes:
            - media_source:/app/media_source
            - streams:/streams
        depends_on:
            - database
            - admin
            - elastic

    flask:
        build:
            context: .
            dockerfile: src/Dockerfile.flask
        env_file:
            - "flask_application/.env_flask_app"
        volumes:
            - flask_app:/app
        depends_on:
            - admin
            - elastic
        ports:
            - "5000:5000"

    nginx:
        image: nginx:1.9.2
        volumes:
            - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./src/site.conf:/etc/nginx/conf.d/site.conf:ro
            - ./flask_application/static/styles.css:/static/styles.css
            - static:/static
            - streams:/streams
        depends_on:
            - admin
        ports:
            - "80:80"


volumes:
    data:
    videos:
    static:
    media_source:
    elastic_data:
    streams:
    flask_app:
