FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
RUN apt update -y && apt upgrade -y && apt install -y ffmpeg
COPY etl .
CMD python etl_process.py
