version: '3'
services:

    database:
        image: postgres:13
        ports:
            - "5432:5432"
        env_file:
            - ".env"
        volumes:
            - data:/var/lib/postgresql/data
        restart: always

    elastic:
        build:
            context: .
            dockerfile: Dockerfile.elastic
        ports:
            - "9200:9200"
        volumes:
            - elastic_data:/usr/share/elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms1000m -Xmx1000m
        depends_on:
            - database
        restart: always

    admin:
        build:
            context: .
            dockerfile: Dockerfile.django_admin
        env_file:
            - ".env"
        depends_on:
            - database
        ports:
            - "8000:8000"
        volumes:
            - videos:/videos
            - static:/app/static
            - media_source:/app/media
        restart: always

    etl:
        build:
            context: .
            dockerfile: Dockerfile.etl
        env_file:
            - "etl/.env_etl"
        volumes:
            - media_source:/app/media_source
            - streams:/streams
        depends_on:
            - database
            - admin
            - elastic
        restart: always

    flask:
        build:
            context: .
            dockerfile: Dockerfile.flask
        env_file:
            - "flask_application/.env_flask_app"
        volumes:
            - flask_app:/app
        depends_on:
            - admin
            - elastic
        ports:
            - "5000:5000"
        restart: always

    nginx:
        image: nginx:1.9.2
        volumes:
            - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./src/site.conf:/etc/nginx/conf.d/site.conf:ro
            - ./flask_application/static/styles.css:/static/styles.css
            - static:/static
            - streams:/streams
        depends_on:
            - admin
        ports:
            - "80:80"
        restart: always


volumes:
    data:
    videos:
    static:
    media_source:
    elastic_data:
    streams:
    flask_app:
