# flake8: noqa
# Generated by Django 4.0.3 on 2022-04-09 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid

from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        RunSQL('CREATE SCHEMA IF NOT EXISTS content'),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=65, verbose_name='Audio track title')),
                ('audio_file', models.FileField(upload_to='audio', verbose_name='Audio track file')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio track',
                'verbose_name_plural': 'Audio tracks',
                'db_table': 'content"."audio_track',
            },
        ),
        migrations.CreateModel(
            name='Langs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_title', models.CharField(max_length=50, verbose_name='Full title')),
                ('iso_639_1', models.CharField(max_length=10, verbose_name='ISO 639-1')),
                ('iso_639_2', models.CharField(blank=True, max_length=10, verbose_name='ISO 639-2')),
            ],
            options={
                'verbose_name': 'Lang',
                'verbose_name_plural': 'Langs',
                'db_table': 'content"."langs',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('h1', models.CharField(max_length=50, verbose_name='h1')),
                ('description', models.TextField(verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_track', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='videos.audiotrack')),
                ('lang', models.ForeignKey(db_column='lang', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='videos.langs', verbose_name='Lang')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
                'db_table': 'content"."video',
            },
        ),
        migrations.CreateModel(
            name='VideoTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=65, verbose_name='Video track title')),
                ('video_file', models.FileField(upload_to='video', verbose_name='Video track file')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.ManyToManyField(related_name='audio_track', through='videos.Video', to='videos.audiotrack')),
            ],
            options={
                'verbose_name': 'Video track',
                'verbose_name_plural': 'Video tracks',
                'db_table': 'content"."video_track',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='video_track',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='videos.videotrack'),
        ),
    ]
