FROM python:3.9-slim

WORKDIR /app

COPY ../requirements.txt .
COPY ../etl .
RUN pip install --upgrade pip && pip install -r requirements.txt
RUN apt update -y && apt upgrade -y && apt install -y ffmpeg
CMD python pass.py