FROM python:3.9-slim

WORKDIR /app
COPY ../pyproject.toml .
COPY ../poetry.lock .

RUN pip install --upgrade pip && pip install poetry
ENV POETRY_VIRTUALENVS_CREATE false
RUN poetry install

COPY ../flask_application .
CMD python3 main.py
